travis:
  secure:
    BINSTAR_TOKEN: PUgdPOkWNjjwd57Trqp7NUa7oL8SOKeZqZq318KiBu6Y6h0LhP/WLRi93y1Ej4lLGFr16NIOi5FFal535MGQHNfMVgmoGMQGOkqGef7RlCffEyuWSNYoiXxBJ3Mfsos8mD47IhcCig2nu2s+FnfyAeiB3Pqat1xjfaM1Wtk6OemZgxCWeafINITqffqtvBtucq97+8CMsOtNkfPPz4PoBVT9oK+2IdVHQXl5U6XZ5zyRnvs8Ijg1mN+IszN+E9GQEHxklvWj3HIuoJkBFcd52sAtvDgv5LDmn21lWMLV/lYJp0yczKWZQCgqLw8V9zffnYz5k6Edbxif2VtViuZr7fwpFy7cawZq8WU3D+5ft13TyTKa4ltR9yvtXjYAJpQUKqUGi1UEwJgLKTOwUiZme4IfAiGcAKX8MCOI3F3w5nYQkxrx1ifCJ0RUxC2IIu9P078wsZlC7DeEHXu3EyYN/VD6HB6FGo0oMKIbLmwyPh6xZL/ajK1zott/4meKZbPBFlSVGcDH8c/ngUtOprXYB6JCs6UTIdWDGwi6OEKCjw0BKGZqTSZL7UkkYW1FP3OohdZymFJWbZFyep27Do+OB9uFCsW9OeiB9TdSVvOD0KlOUAx3QHsmFvzTJRSI+HhMuxmLaNnxR0VCZWAuFZdF9xF7glo/JmStpblniaPAfio=
appveyor:
  secure:
    BINSTAR_TOKEN: Rb//syQhmC53YylTgEkPLNDCZqF65mRSPN2lAvEvSap9MtP3Pth2D/UVZlepmalL
channels:
  targets:
    - [nomr, main]
